#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  1 15:15:34 2021

@author: yimingteng
"""

list=['Hawking','Winberg','Penrous','Einstein']
i=0
while i<4:
    print(list[i])
    i=i+1