#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  1 15:15:34 2021

@author: yimingteng
"""

list=['Hawking','Winberg','Penrous','Einstein']
i=0
while i<4:
    print(list[i])
    i=i+1
i=0

print(list.pop(2)+" can't come, but Newton will")
list.insert(2, 'Newton')
print("The list is:")
while i<4:
    print(list[i])
    i=i+1
i=0

print("I've found a bigger table! We gonna invite 3 more guests!")
list.insert(0, 'Singer')
list.insert(2,'Atyah')
list.append('Laplace')
while i<7:
    print(list[i])
    i=i+1
i=0

print("Holy crap! I can only invite 2 guests... Sorry bro~")
while i<=4:
    print("Sorry, "+list.pop(0))
    i=i+1
i=0
print(list[0]+" you are invited!")
print(list[1]+" you're invited!")
list.remove('Einstein')
list.remove('Laplace')
print(list)
    