#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  1 14:34:42 2021

@author: yimingteng
"""

famous_person="IDK"
motto="\"Si vis pacem, para bellum\""
print(famous_person+" once said, "+motto)